/*PROBLEM2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*/


# include<stdio.h>

int main(){
    int i,sum,sayi1,sayi2,gecici;
    sum =0;
    sayi1 = 1;
    sayi2 = 1;
    gecici=0;
    while(gecici<4000000){
        gecici = sayi1+sayi2;
        
        if(gecici % 2 == 0){
            
            sum += gecici;
        }
        sayi1 = sayi2;
        sayi2 = gecici;
    }
    printf("%d\n",sum);

    return 0;
}